version: "3"
services:
  postgresdb:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  auth-server:
    container_name: auth_microservice
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    ports:
      - 5000:5000
    volumes:
      - /usr/src/app/node_modules
      - ./services/auth:/usr/src/app
